// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TestMVC.MvcEduModels
{
    public partial class Account
    {
        /// <summary>
        /// 帳號ID
        /// </summary>
        public int ID { get; set; }
        /// <summary>
        /// 會員帳戶
        /// </summary>
        public string Account1 { get; set; }
        /// <summary>
        /// 會員帳戶密碼
        /// </summary>
        public string Password { get; set; }
        /// <summary>
        /// 狀態(使用中，停權)
        /// </summary>
        public string Status { get; set; }
    }
}