// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TestMVC.MvcEduModels
{
    public partial class Audit
    {
        /// <summary>
        /// 權限編號
        /// </summary>
        public int Audit_ID { get; set; }
        /// <summary>
        /// 權限(admin,supervisor,emp,member)
        /// </summary>
        public string Audit1 { get; set; }
        /// <summary>
        /// 狀態
        /// </summary>
        public string Status { get; set; }
    }
}