// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TestMVC.MvcEduModels
{
    public partial class Course
    {
        /// <summary>
        /// 課程ID
        /// </summary>
        public int ID { get; set; }
        /// <summary>
        /// 課程名稱
        /// </summary>
        public string CourseName { get; set; }
        /// <summary>
        /// 授課教師
        /// </summary>
        public string Teacher { get; set; }
        /// <summary>
        /// 課程時數(小時)
        /// </summary>
        public string CourseHour { get; set; }
        /// <summary>
        /// 課程類型(CourseCatalog.CatalogID)
        /// </summary>
        public string CourseCatalog { get; set; }
        /// <summary>
        /// 課程描述
        /// </summary>
        public string CourseDesc { get; set; }
        /// <summary>
        /// 課程定價
        /// </summary>
        public int CoursePrice { get; set; }
        /// <summary>
        /// 是否需要認證(Y,N)
        /// </summary>
        public string Certificate { get; set; }
        /// <summary>
        /// 課程起始日期
        /// </summary>
        public DateTime Date_Start { get; set; }
        /// <summary>
        /// 課程結束日期
        /// </summary>
        public DateTime Date_End { get; set; }
        /// <summary>
        /// 課程狀態(是否開課) Y,N
        /// </summary>
        public string CourseStatus { get; set; }
        /// <summary>
        /// 開課人數
        /// </summary>
        public int StudentCapacity { get; set; }
        /// <summary>
        /// 狀態
        /// </summary>
        public string Status { get; set; }
    }
}