// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TestMVC.MvcEduModels
{
    public partial class CourseCatalog
    {
        /// <summary>
        /// 編號
        /// </summary>
        public int ID { get; set; }
        /// <summary>
        /// 課程類型名稱(語言，資安，作業系統，資料庫，…)
        /// </summary>
        public string Name { get; set; }
    }
}