// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TestMVC.MvcEduModels
{
    public partial class Dept
    {
        /// <summary>
        /// 部門編號
        /// </summary>
        public int Dept_ID { get; set; }
        /// <summary>
        /// 部門名稱
        /// </summary>
        public string Dept_Name { get; set; }
    }
}