// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TestMVC.MvcEduModels
{
    public partial class Employee
    {
        /// <summary>
        /// 編號
        /// </summary>
        public int ID { get; set; }
        /// <summary>
        /// 員工名字
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// 生日
        /// </summary>
        public DateTime Birthday { get; set; }
        /// <summary>
        /// 員工手機
        /// </summary>
        public string Cellphone { get; set; }
        /// <summary>
        /// 員工電話
        /// </summary>
        public string Telephone { get; set; }
        /// <summary>
        /// 員工Line
        /// </summary>
        public string LineID { get; set; }
        /// <summary>
        /// 住址
        /// </summary>
        public string Address { get; set; }
        /// <summary>
        /// 員工Email
        /// </summary>
        public string Email { get; set; }
        /// <summary>
        /// 職位
        /// </summary>
        public string Position { get; set; }
        /// <summary>
        /// 部門ID
        /// </summary>
        public string Dept { get; set; }
        /// <summary>
        /// 學歷
        /// </summary>
        public string Education { get; set; }
        /// <summary>
        /// 權限
        /// </summary>
        public string Audit { get; set; }
        /// <summary>
        /// 薪資
        /// </summary>
        public int Salary { get; set; }
        /// <summary>
        /// 上級(ID)
        /// </summary>
        public int? Supervisor { get; set; }
        /// <summary>
        /// 緊急聯絡人
        /// </summary>
        public string EmergencyContact { get; set; }
        /// <summary>
        /// 緊急連絡人電話
        /// </summary>
        public string EmergencyCell { get; set; }
        /// <summary>
        /// 緊急連絡人關係
        /// </summary>
        public string Relation { get; set; }
        /// <summary>
        /// 員工狀態(在職，離職，留職停薪)
        /// </summary>
        public string EmpStatus { get; set; }
        /// <summary>
        /// 入職日期
        /// </summary>
        public DateTime HireDate { get; set; }
        /// <summary>
        /// 休假剩餘天數
        /// </summary>
        public string SpecialDayoff { get; set; }
        /// <summary>
        /// 員工照片
        /// </summary>
        public byte[] Photo { get; set; }
        /// <summary>
        /// 帳號
        /// </summary>
        public string Account { get; set; }
        public string Type { get; set; }
        /// <summary>
        /// 狀態
        /// </summary>
        public string Status { get; set; }
    }
}