// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TestMVC.MvcEduModels
{
    public partial class Member
    {
        /// <summary>
        /// 會員ID
        /// </summary>
        public int ID { get; set; }
        /// <summary>
        /// 會員姓名
        /// </summary>
        public string UserName { get; set; }
        /// <summary>
        /// 性別
        /// </summary>
        public string Gender { get; set; }
        /// <summary>
        /// 生日日期
        /// </summary>
        public DateTime BirthDate { get; set; }
        /// <summary>
        /// 住址
        /// </summary>
        public string Address { get; set; }
        /// <summary>
        /// 電子郵件
        /// </summary>
        public string Email { get; set; }
        /// <summary>
        /// 手機號碼
        /// </summary>
        public string Cellphone { get; set; }
        /// <summary>
        /// 市話
        /// </summary>
        public string Telephone { get; set; }
        /// <summary>
        /// Line
        /// </summary>
        public string LineID { get; set; }
        /// <summary>
        /// 教育程度
        /// </summary>
        public string Education { get; set; }
        /// <summary>
        /// 會員等級(鑽石，白金，金，銀，無)
        /// </summary>
        public string Membership { get; set; }
        /// <summary>
        /// 會費
        /// </summary>
        public int Fee { get; set; }
        /// <summary>
        /// 帳戶
        /// </summary>
        public string Account { get; set; }
        public string Password { get; set; }
        /// <summary>
        /// 加入日期
        /// </summary>
        public DateTime JoinDate { get; set; }
        /// <summary>
        /// 會員大頭照
        /// </summary>
        public byte[] Photo { get; set; }
        /// <summary>
        /// 狀態
        /// </summary>
        public string Status { get; set; }
        /// <summary>
        /// 類型
        /// </summary>
        public string Type { get; set; }
    }
}