// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TestMVC.MvcEduModels
{
    public partial class Member_Course
    {
        /// <summary>
        /// 編號
        /// </summary>
        public int ID { get; set; }
        /// <summary>
        /// 會員名稱
        /// </summary>
        public string MemberName { get; set; }
        /// <summary>
        /// 課程編號
        /// </summary>
        public int CourseID { get; set; }
        /// <summary>
        /// 課程名稱
        /// </summary>
        public string CourseName { get; set; }
        /// <summary>
        /// 教室編號
        /// </summary>
        public int ClassroomID { get; set; }
        /// <summary>
        /// 是否得到認證(Y,N)
        /// </summary>
        public string Certificate { get; set; }
        /// <summary>
        /// 考試分數
        /// </summary>
        public double? Score { get; set; }
        /// <summary>
        /// 課程起始日期
        /// </summary>
        public DateTime Date_Start { get; set; }
        /// <summary>
        /// 課程結束日期
        /// </summary>
        public DateTime Date_End { get; set; }
        /// <summary>
        /// 會員上課狀態(在學，畢業，中離)
        /// </summary>
        public string MemberStatus { get; set; }
        /// <summary>
        /// 狀態
        /// </summary>
        public string Status { get; set; }
    }
}