// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TestMVC.MvcEduModels
{
    public partial class School
    {
        /// <summary>
        /// 編號
        /// </summary>
        public int ID { get; set; }
        /// <summary>
        /// 學校名稱
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// 學校類型(高中，專科，大學，研究所)
        /// </summary>
        public string SchoolType { get; set; }
        /// <summary>
        /// 狀態
        /// </summary>
        public string Status { get; set; }
    }
}