// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TestMVC.MvcEduModels
{
    public partial class Teacher
    {
        /// <summary>
        /// 編號
        /// </summary>
        public int ID { get; set; }
        /// <summary>
        /// 教師名字
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// 學歷
        /// </summary>
        public string Education { get; set; }
        /// <summary>
        /// 教師生日
        /// </summary>
        public DateTime Birthday { get; set; }
        /// <summary>
        /// 專長(語言，資安，資料庫...)
        /// </summary>
        public string Expertise { get; set; }
        /// <summary>
        /// 教師經歷
        /// </summary>
        public string Experience { get; set; }
        /// <summary>
        /// 是否在職(Y,N)
        /// </summary>
        public string TeacherStatue { get; set; }
        /// <summary>
        /// 教師Email
        /// </summary>
        public string Email { get; set; }
        /// <summary>
        /// 教師電話(手機號碼)
        /// </summary>
        public string Telephone { get; set; }
        /// <summary>
        /// 教師Line
        /// </summary>
        public string LineID { get; set; }
        /// <summary>
        /// 教師大頭照
        /// </summary>
        public byte[] Photo { get; set; }
        /// <summary>
        /// 狀態
        /// </summary>
        public string Status { get; set; }
    }
}